name: Build Avalonia App

on:
  push:
    branches:
      - master  # или другая ветка, с которой вы хотите собирать
  pull_request:
    branches:
      - master  # или другая ветка для PR

jobs:
  build:
    runs-on: ubuntu-latest  # или windows-latest или macos-latest, в зависимости от цели

    strategy:
      matrix:
        os: [linux, win, osx]  # Указание всех платформ для CI

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0'  # Убедитесь, что указываете версию SDK, например, 9.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish for ${{ matrix.os }}-x64
      run: dotnet publish --configuration Release --runtime ${{ matrix.os }}-x64 --self-contained --output ./publish/${{ matrix.os }}

    # Загружаем артефакты (сборка и публикация)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: publish-${{ matrix.os }}  # Название артефакта
        path: ./publish/${{ matrix.os }}  # Путь к файлам
