name: Build macOS Bundle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Publish
      run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=false
      
    - name: Create macOS bundle
      run: |
        APP_NAME="DesktopPet"
        PUBLISH_DIR="./bin/Release/net9.0/osx-x64/publish"
        APP_DIR="./bin/Release/${APP_NAME}.app"
        CONTENTS_DIR="${APP_DIR}/Contents"
        MACOS_DIR="${CONTENTS_DIR}/MacOS"
        RESOURCES_DIR="${CONTENTS_DIR}/Resources"

        mkdir -p "${MACOS_DIR}" "${RESOURCES_DIR}"
        cp -r "${PUBLISH_DIR}"/* "${MACOS_DIR}/"
        cp "./AppIcon.icns" "${RESOURCES_DIR}/"
        cp "./Info.plist" "${CONTENTS_DIR}/"
      
    - name: Compress bundle for upload
      run: cd ./bin/Release && zip -r "${APP_NAME}.zip" "${APP_NAME}.app"
      
    - name: Upload bundle artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-app-bundle
        path: ./bin/Release/${APP_NAME}.zip